### ISSUE TITLE
Functions to systematically test player strength

### ISSUE THREAD

**Issue by tscode** [roSievers/Jtac.jl#11]
It would be nice to have `duel` / `tournament` functions where a number of players can participate, and from which victory-statistics (or even elo numbers?) can be derived.

**Comment by tscode** [comment]
We should look at Bayesian Elos for this.

**Comment by tscode** [comment]
Bayesian Elo seems to work reasonably well. Time to incorporate it in the main library.

**Comment by roSievers** [comment]
Implemented with b647c2dc1132adbdbdce1e523e7d113009b3b2d4
