### ISSUE TITLE
Get improved values from players

### ISSUE THREAD

**Issue by tscode** [roSievers/Jtac.jl#27]
Currently, players can not be asked about values of states. However, MCTSPlayers with high power should be able to give more precise value information ("improved values") than the model they are built upon, an analog to improved policies.

**Comment by tscode** [comment]
This is, for example, important if the player is asked the value of a state for interpretation in the AI-Server.

**Comment by kreibaum** [comment]
Sounds reasonable, do we already have a theoretical basis for this improved value?

**Comment by tscode** [comment]
`MCTSPlayer`s (and `IntuitionPlayer`s) can as of a72f7e999f7d76b7a98e13711e09f927716fe205 be asked for game state values via `Player.evaluate(player, game)`, which returns a named `(value, policy)` tuple. The value is calculated as average of `root.expected_reward` of the expanded root node, weighted by `policy`.

This probably leads to a value prediction that is somewhat too soft (due to exploration and policy-averaging), but it has the interpretation of an expected outcome (under the networks value beliefs) when the MCTS policies are followed.
